# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import channel_pb2 as channel__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in channel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/oasis.network.CoordinatorService/Register',
                request_serializer=channel__pb2.WorkerInfo.SerializeToString,
                response_deserializer=channel__pb2.WorkerConfig.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/oasis.network.CoordinatorService/Heartbeat',
                request_serializer=channel__pb2.WorkerId.SerializeToString,
                response_deserializer=channel__pb2.Empty.FromString,
                _registered_method=True)
        self.WaitForRound = channel.unary_unary(
                '/oasis.network.CoordinatorService/WaitForRound',
                request_serializer=channel__pb2.WorkerId.SerializeToString,
                response_deserializer=channel__pb2.RoundInfo.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/oasis.network.CoordinatorService/GetContext',
                request_serializer=channel__pb2.ContextRequest.SerializeToString,
                response_deserializer=channel__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.SendAction = channel.unary_unary(
                '/oasis.network.CoordinatorService/SendAction',
                request_serializer=channel__pb2.ActionRequest.SerializeToString,
                response_deserializer=channel__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.RoundComplete = channel.unary_unary(
                '/oasis.network.CoordinatorService/RoundComplete',
                request_serializer=channel__pb2.RoundResult.SerializeToString,
                response_deserializer=channel__pb2.Empty.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/oasis.network.CoordinatorService/Unregister',
                request_serializer=channel__pb2.WorkerId.SerializeToString,
                response_deserializer=channel__pb2.Empty.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """1. Worker Registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """2. Heartbeat to keep worker alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForRound(self, request, context):
        """3. Long-polling for next round signal. Server holds response until round starts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """4. Fetch agent context directly (followers, groups)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """5. Submit action to Platform and get result synchronously
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RoundComplete(self, request, context):
        """6. Signal that worker finished all its active agents for the round
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """7. Graceful worker unregistration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=channel__pb2.WorkerInfo.FromString,
                    response_serializer=channel__pb2.WorkerConfig.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=channel__pb2.WorkerId.FromString,
                    response_serializer=channel__pb2.Empty.SerializeToString,
            ),
            'WaitForRound': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForRound,
                    request_deserializer=channel__pb2.WorkerId.FromString,
                    response_serializer=channel__pb2.RoundInfo.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=channel__pb2.ContextRequest.FromString,
                    response_serializer=channel__pb2.ContextResponse.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=channel__pb2.ActionRequest.FromString,
                    response_serializer=channel__pb2.ActionResponse.SerializeToString,
            ),
            'RoundComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.RoundComplete,
                    request_deserializer=channel__pb2.RoundResult.FromString,
                    response_serializer=channel__pb2.Empty.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=channel__pb2.WorkerId.FromString,
                    response_serializer=channel__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oasis.network.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oasis.network.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oasis.network.CoordinatorService/Register',
            channel__pb2.WorkerInfo.SerializeToString,
            channel__pb2.WorkerConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oasis.network.CoordinatorService/Heartbeat',
            channel__pb2.WorkerId.SerializeToString,
            channel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oasis.network.CoordinatorService/WaitForRound',
            channel__pb2.WorkerId.SerializeToString,
            channel__pb2.RoundInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oasis.network.CoordinatorService/GetContext',
            channel__pb2.ContextRequest.SerializeToString,
            channel__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oasis.network.CoordinatorService/SendAction',
            channel__pb2.ActionRequest.SerializeToString,
            channel__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RoundComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oasis.network.CoordinatorService/RoundComplete',
            channel__pb2.RoundResult.SerializeToString,
            channel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oasis.network.CoordinatorService/Unregister',
            channel__pb2.WorkerId.SerializeToString,
            channel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
